// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// distan_np
double distan_np(DataFrame df);
RcppExport SEXP _clouds_distan_np(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(distan_np(df));
    return rcpp_result_gen;
END_RCPP
}
// EMD
double EMD(DataFrame df);
RcppExport SEXP _clouds_EMD(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(EMD(df));
    return rcpp_result_gen;
END_RCPP
}
// corregir
double corregir(int n_1, int n_2, double d);
RcppExport SEXP _clouds_corregir(SEXP n_1SEXP, SEXP n_2SEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_1(n_1SEXP);
    Rcpp::traits::input_parameter< int >::type n_2(n_2SEXP);
    Rcpp::traits::input_parameter< double >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(corregir(n_1, n_2, d));
    return rcpp_result_gen;
END_RCPP
}
// cloud_distance_
double cloud_distance_(DataFrame df);
RcppExport SEXP _clouds_cloud_distance_(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(cloud_distance_(df));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_clouds_distan_np", (DL_FUNC) &_clouds_distan_np, 1},
    {"_clouds_EMD", (DL_FUNC) &_clouds_EMD, 1},
    {"_clouds_corregir", (DL_FUNC) &_clouds_corregir, 3},
    {"_clouds_cloud_distance_", (DL_FUNC) &_clouds_cloud_distance_, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_clouds(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
