# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distan_np <- function(df) {
    .Call('_clouds_distan_np', PACKAGE = 'clouds', df)
}

EMD <- function(df) {
    .Call('_clouds_EMD', PACKAGE = 'clouds', df)
}

corregir <- function(n_1, n_2, d) {
    .Call('_clouds_corregir', PACKAGE = 'clouds', n_1, n_2, d)
}

cloud_distance_ <- function(df) {
    .Call('_clouds_cloud_distance_', PACKAGE = 'clouds', df)
}

